USE ROLE DEMO_ROLE


--Step 1 SECRETS


CREATE OR REPLACE SECRET HENRYL_GITHUB_SECRET
TYPE = PASSWORD
USERNAME = 'Henryl-Pereira'
PASSWORD = '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';


SHOW SECRETS;

DECRIBE SECRET HENRYL_GITHUB_SECRET;




--Step 2 git api


CREATE OR REPLACE API INTEGRATION HENRYL_GITHUB_API_INTEGRATION
API_PROVIDER = GIT_HTTPS_API
API_ALLOWED_PREFIXES = ('https://github.com/Henryl-Pereira'
ALLOWED_AUTHENTICATION_SECRETS= (HENRYL_GITHUB_SECRET)
ENABLED = TRUE;


SHOW INTEGRATIONS;

SHOW API INTEGRATIONS;

DESCRIBE API INTEGRATION HENRYL_GITHUB_API_INTEGRATION;




--Step 3 Git repo

CREATE OR REPLACE GIT REPOSITORY DEMO_REPO
API_INTEGRATION = HENRYL_GITHUB_API_INTEGRATION
GIT_CREDENTIALS = HENRYL_GITHUB_SECRET
ORIGIN = 'https://github.com/Henryl-Pereira/demo-repo'

SHOW GIT REPOSITORIES;

DESCRIBE GIT REPOSITORY DEMO_REPO;

GRANT READ ON GIT REPOSITORY DEMO_REPO TO ROLE DEMO_ROLE;

USE ROLE DEMO_ROLE;


--step 4 


LIST @DEMO_REPO/branches/main;

LIST @DEMO_REPO/tags/tag_name;

LIST @DEMO_REPO/comits/comit_hash;



SHOW GIT BRANCHES IN DEMO_REPO;

SHOW GIT TAGS IN DEMO_REPO;


ALTER GIT REPOSITORY DEMO_REPO FETCH;

